# Site settings
title: Andy Design
email: ldehai@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just do it
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ldehai.com" # the base hostname & protocol for your site
twitter_username: ldehai
github_username:  ldehai

# Build settings
markdown: kramdown
