# Basic
title: ldehai
subtitle: 让每个人都能接受平等的教育
welcome_message: 我正在写一本书《每个人都会编程》
description: 嗨，我是刘德海 (@ldehai)，iOS / Mac 独立开发者，现居南京。我创建了AventLabs，一个在线学习编程和设计的平台，主要面向初学者。
creator: <a href="http://stackoverflow.com/story/ldehai">@ldehai</a>

url: "http://ldehai.com"

permalink: blog/:year/:month/:day/:title/

# Format
highlighter: plain

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问我的博客

# Navigation buttons in the front page.
nav:
    - {title: 作品, description: 我目前的iOS作品, url: 'https://itunes.apple.com/cn/developer/andy-liu/id521680917?l=en'}
    - {title: AventLabs, description: 一个面向初学者在线学习编程和设计的平台, url: 'https://www.aventlabs.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: ldehai
    # duoshuo:

# Social
social:
    weibo: ldehai
    github: ldehai
    twitter: ldehai
    # gplus: 107108267983477358170
    mail: ldehai@gmail.com

# Google Analytics
ga:
    id: UA-44047356-1
    host: ldehai.com
